# Generated by Django 4.2.7 on 2023-11-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="difficulty",
        ),
    ]
