# Generated by Django 4.2.7 on 2023-12-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(
                default="./static/recipes/images/no_picture.jpg", upload_to="recipes"
            ),
        ),
    ]
