# Generated by Django 4.2.7 on 2023-12-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(default="This recipe promises not to dissappoint"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(default="no_picture.jpg", upload_to="recipes"),
        ),
    ]
