# Generated by Django 4.2.7 on 2024-01-10 19:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_recipe_description_alter_recipe_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="pic",
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name="pic"),
        ),
    ]
